version: 0.2

phases:
  build:
    commands:
      - echo "📦 Build block"
      - ls -la
      - echo '🧪 Checking if "Congratulations" is present in index.html'
      - if [ -f index.html ]; then grep "Congratulations" index.html; else echo "index.html not found"; fi
  post_build:
    commands:
      - echo "✅ Post build phase"

artifacts:
  files:
    - '**/*'
  discard-paths: yes

