version: 0.2

phases:
  build:
    commands:
      - echo "Build phase started"
      - ls -la
      - echo "Running test: checking 'Congratulations' in index.html (if exists)"
      - grep "Congratulations" index.html || echo "'Congratulations' not found or index.html missing"

  post_build:
    commands:
      - echo "Post build phase completed"

artifacts:
  files:
    - appspec.yml
    - scripts/**     # includes all scripts
    - '**/*.html'    # in case you're deploying HTML files
  discard-paths: no

