version: 0.2

phases:
  build:
    commands:
      - echo "Build block"
      - ls
      - |
        echo "Running tests to check if 'Congratulations' is present in index.html"
        grep "Congratulations" index.html || echo "Test failed"
  post_build:
    commands:
      - echo "Post build phase"

artifacts:
  files:
    - appspec.yml
    - scripts/**
    - '**/*.html'
    - target/**/*
  discard-paths: no


