version: 0.2

phases:
  build:
    commands:
      - echo "📦 Build block"
      - echo "📁 Current directory contents:"
      - ls -la
      - echo "🧪 Checking for 'Congratulations' in index.html"
      - if [ -f index.html ]; then cat index.html; else echo "❌ index.html not found"; fi
      - grep "Congratulations" index.html || echo "🔍 'Congratulations' not found or error, but continuing"

  post_build:
    commands:
      - echo "✅ Post build phase"

artifacts:
  files:
    - '**/*'
  discard-paths: yes

